### ISSUE TITLE
Unable to install - could not find driver

### ISSUE THREAD

**Issue by richdynamix** [cnvs/easel#93]
When running `php artisan canvas:install` I get the following - 

```
root@2736700b8911:/app# php artisan canvas:install

Welcome to the Canvas Install Wizard! You'll be up and running in no time...

Setting up your database...

An unexpected error occurred. Installation could not continue.
✘ could not find driver

Migrations were rolled back. Please run the installer again.

If this error persists please consult https://github.com/cnvs/easel/issues.
```

If I run it again, it asks me to add admin user details but then immediately shows the same error - `could not find driver`. There is nothing in the logs to investigate further.

**Comment by richdynamix** [comment]
Debugging seems to point me to when the DB is trying to seed or the user is created. The user is created in the DB though. Will update when I have more info.

**Comment by austintoddj** [comment]
@richdynamix Thanks for checking out Canvas! I'll take a look at this today and see if I can find a solution for you.

**Comment by austintoddj** [comment]
@richdynamix What type of DB are you installing Canvas on?

**Comment by richdynamix** [comment]
Hi @austintoddj I am installing this on a MySQL 5.7 DB. My project setup is with Docker.

_loving the new webiste btw_ ;)

**Comment by austintoddj** [comment]
Thanks @richdynamix, glad you like the new site! Haven't actually done my own installations on Docker, so I don't have a ton of familiarity with it. I will keep digging though and see what I come up with.

**Comment by richdynamix** [comment]
Hey @austintoddj Did you manage find any resolution to this issue? Really keen to build my next blog with Canvas 😁

**Comment by austintoddj** [comment]
@richdynamix Did the error you encountered happen using `v3.2.10`?

**Comment by unrivaledcreations** [comment]
Ditto this issue; although my configuration is slightly different.  I'm running a VirtualBox instance of an Ubuntu PHP 7.1 box on a Mac, provisioned with Vagrant via Puphpet.  The source files in this setup are on the Mac's native filesystem, mapped to a folder within the virtualized guest OS and configured as the www root in its nginx config.  Because of this arrangement, the `composer create-project --prefer-dist cnvs/canvas blog` command must be run on the host OS (the Mac), but then you must ssh into the Vagrant box (virtualized guest OS) to run `php artisan canvas:install`.  If you try to run `php artisan canvas:install` from the host OS (on your main computer), it can't connect to the correct MySQL database since that runs in the virtualized guest OS (or, in the case of @richdynamix a Dockerized container; try `docker exec -it {container name} bash`, find your blog Laravel project folder, then try `php artisan canvas:install` from there - see if that works!).

It's worth noting that the [installation instructions](https://cnvs.readme.io/docs/installation) do not warn you to `cd blog` after the composer command finishes, in order to proceed with the canvas:install.  You might want to mention that.

Even after successfully creating the project, as with @richdynamix, I am also unable to `php artisan canvas:install` and get the same error message:

> An unexpected error occurred. Installation could not continue.
✘ could not find driver

This happens only after it asks for my email address, a password, a first name and a last name.  POW!  Right then and there; an error about finding the driver.

- A series of DB tables are created in MariaDB (MySQL)
- canvas_posts has 1 row (a 'hello world' post)
- canvas_users has 1 row (a user, but it only has the email address in it; no password, no first or last name)
- canvas_migrations has 17 rows (weird stuff, apparently dating back to 2016)

Hope that helps you get to the bottom of things!

**Comment by austintoddj** [comment]
@unrivaledcreations First off, thanks for the extremely detailed and well-worded response, it's a huge help. Hopefully I can answer what questions you have and we can get to the bottom of this.

As for what you're seeing in the database:
* A fresh installation will yield just enough blog data to get you started and understand what's going on
* The migrations table holds records of all the database changes in the application and throughout its development. [See more here](https://laravel.com/docs/5.4/migrations)

Do you have each of these extensions installed in your VirtualBox that you're running Canvas in? 

* PHP extensions ([PDO](http://php.net/manual/en/book.pdo.php), [SQLite](http://php.net/manual/en/book.sqlite.php), [OpenSSL](http://php.net/manual/en/book.openssl.php), [Mbstring](http://php.net/manual/en/book.mbstring.php), [Tokenizer](http://php.net/manual/en/book.tokenizer.php), [Zip](http://php.net/manual/en/book.zip.php))

**Comment by unrivaledcreations** [comment]
SQLite and Zip were both missing.  Mbstring would normally be missing from a stock PuPHPet configuration, too, except I'd already added that to make phpMyAdmin work.

For others using PuPHPet to manage your dev environment, edit your `config.yaml` file and add these lines:

- Under php:modules:php, add `- mbstring` and `- sqlite`
- Under php:modules:pecl, add `- zip`

@richdynamix, if you're using a Docker container, you'll have to find a container that has all these extensions already installed for you, or you'll have to add them yourself (and document those steps so you remember to do it again later when using future container updates).  Good luck to you!

**Comment by austintoddj** [comment]
Thanks for the update @unrivaledcreations. I'll definitely look into adding a check into the `canvas:install` process. 👍

**Comment by kyushiro** [comment]
I am having the exact same issue while trying to install. Everything goes smoothly, i added the db credentials to the .env file, and then do`php artisan canvas:install`  
and of course i get the same error again. For the record i am doing this on a digitalocean 1gb ubuntu 16.04 droplet, and php modules list seems ok except maybe that i have "sqlite2" rather than simply "sqlite" installed. could this be the issue?

I will try to look deeper into this later today
